### ISSUE TITLE
Create catalog of cat foods

### ISSUE THREAD

**Issue by baskauf** [baskauf/practice#9]
Hey, @baskaufs, our next task should be developing the comprehensive database of cat foods.  I'll take the lead on this one.

**Comment by baskaufs** [comment]
Tomy, I really think you had better get started on #10 before you start in on this.

**Comment by baskauf** [comment]
OK, boss.  Whatever you say.

**Comment by baskaufs** [comment]
I changed my mind.  I think this should be done soon.

**Comment by baskauf** [comment]
I'm so excited about this!

**Comment by baskauf** [comment]
Mission accomplished: [catfood list](https://github.com/baskauf/practice/blob/master/cat-fude.txt)
